scheduler:
  metric: DominantShares
  method: batch
  log_warning_every_n_allocated_tasks: 100
  scheduler_timeout_seconds: 10000
  data_lifetime: 10
  scheduling_wait_time: 10
  n: 1000

metric:
  normalize_by: available_budget
  temperature: 0.01
  n_knapsack_solvers: 1


blocks:
  initial_num: 10
  max_num: 10


tasks:
  data_path: alibaba-privacy-workload/outputs/privacy_tasks.csv
  sampling: ""
  block_selection_policy: LatestBlocksFirst
  avg_num_tasks_per_block: 100

logs:
  verbose: True
  save: True